config/routes.rb
OauthPoc::Application.routes.draw do
  resources :api_accounts, only: [:index, :new, :show, :destroy]

  get 'auth/:provider/callback', to: 'api_accounts#create'
  get 'auth/failure', to: 'api_accounts#new'

  root 'api_accounts#index'

  

end

app/models/api_account.rb
class ApiAccount < ActiveRecord::Base
end

app/models/survey_monkey_service.rb
class SurveyMonkeyService
  BASE_API_URL = "https://api-surveymonkey-net-fytofsd4ktc2.runscope.net"

  def init(token)
    @token = token
  end

  def make_request(endpoint, data)
    HTTParty.post("#{BASE_API_URL}#{endpoint}",
        :query => {:api_key => ENV['SURVEY_MONKEY_API_KEY']},
        :body => JSON.dump(data),
        :headers => { "Authorization" => "Bearer #{@token}", "Content-Type" => "application/json"}
      )  
  end

  def get_survey_list(data)
    make_request("/v2/surveys/get_survey_list", data)
  end
end

app/controllers/api_account_controller.rb
class ApiAccountController < ApplicationController
  before_filter :find_api_account, :only => [:show, :destroy]

  def index
    @api_accounts = ApiAccount.all
  end

  def new
    @errors = params[:message]    
  end

  def show  
    @response = HTTParty.post("https://api.surveymonkey.net/v2/surveys/get_survey_list",
        :query => {:api_key => ENV['SURVEY_MONKEY_API_KEY']},
        :headers => { "Authorization" => @api_account.oauth_token, "Content-Type" => "application/json"}
      )  
  end

  def create
    Rails.logger.info "#{auth_hash.inspect}"
    @auth_hash = auth_hash
    @api_account = ApiAccount.find_or_create_by_username(@auth_hash[:info][:client])
    @api_account.oauth_token = @auth_hash[:credentials][:token]
    if @api_account.save
      flash[:message] = "Credentials saved!"
    else
      flash[:message] = "There was a problem saving the credentials."
      render :new
    end
  end

  def destroy
    @api_account.destroy
    redirect_to api_accounts_path
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end

  def find_api_account
    @api_account = ApiAccount.find(params[:id])
  end
end

app/controllers/api_accounts_controller.rb
class ApiAccountsController < ApplicationController
  before_filter :find_api_account, :only => [:show, :destroy]

  def index
    @api_accounts = ApiAccount.all
  end

  def new
    @errors = params[:message]    
  end

  def show  
    data = {"order_asc" => true}
    service = SurveyMonkeyService.new(@api_account.oauth_token)
    @response = service.get_survey_list(data)
  end

  def create
    Rails.logger.info "#{auth_hash.inspect}"
    @auth_hash = auth_hash
    @api_account = ApiAccount.find_or_create_by_username(@auth_hash[:info][:client])
    @api_account.oauth_token = @auth_hash[:credentials][:token]
    if @api_account.save
      flash[:message] = "Credentials saved!"
    else
      flash[:message] = "There was a problem saving the credentials."
      render :new
    end
  end

  def destroy
    @api_account.destroy
    redirect_to api_accounts_path
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end

  def find_api_account
    @api_account = ApiAccount.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/api_account_helper.rb
module ApiAccountHelper
end

app/helpers/api_accounts_helper.rb
module ApiAccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/api_accounts/create.html.haml
%h1 Credentials Saved!
%p You can now close this window or select another link.

app/views/api_accounts/index.html.haml
%h1 API Accounts

%ul
  - @api_accounts.each do |api_account|
    %li= "#{link_to api_account.username, api_account_path(api_account)}, #{api_account.oauth_token}"

= link_to("Get or refresh Survey Monkey token", "/auth/surveymonkey2", target: "_new")

app/views/api_accounts/new.html.haml
%h1 Oops!
%p There appears to have been a problem saving the credentials:

%h2 ERRORS
= @errors

app/views/api_accounts/show.html.haml
%h1 ApiAccount#show
%p Find me in app/views/api_account/show.html.haml

= @response.inspect

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OauthPoc</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>